name: Build and Release PDF

on:
  push:
    tags:
      - 'v*' # 匹配 v 开头的标签，如 v1.0, v2.1

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    container:
      image: danteev/texlive:full # 包含完整 LaTeX 环境的镜像
      options: --user root

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Compile LaTeX document
      run: |
        # 安装中文字体支持（如果文档使用中文）
        apt-get update && apt-get install -y fonts-wqy-zenhei
        # 编译主文档（运行两次确保引用正确）
        xelatex -interaction=nonstopmode main.tex
        xelatex -interaction=nonstopmode main.tex
        # 检查是否生成PDF
        if [ ! -f main.pdf ]; then
          echo "❌ PDF 文件未生成，编译失败"
          exit 1
        fi

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ github.ref_name }} Release
        tag_name: ${{ github.ref_name }}
        files: main.pdf
        draft: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
